### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by zhovner** [zhovner/magic-setup-assistant#8]
Maybe full screen mode is the better way to run electron application? 
But how to deal with different resolutions? 

Here is the background image [app/resources/background.png](https://github.com/zhovner/magic-setup-assistant/blob/master/app/resources/background.png)

**Comment by zhovner** [comment]
Fullscreen mode is working now but only when electron running inside any window manager like gnome, kde, unity etc. In current configuration electron starts in raw `Xorg` environment without window manager and image background not displayed. 

To resolve this issue I plan to use lightweight windows manager like `openbox`.  Also I will try to figure out how Xorg works with resolution downscale and HiDPI configurations.  @TheBeastOfCaerbannog

**Comment by zhovner** [comment]
`openbox` works as temporary solution, but it's not the best way I think.   
Because it delayed Electron start  and it's blink while loading. Need to ask `Xorg` guru how to keep naked `Xorg` without windows manager.

**Comment by zhovner** [comment]
I found another solution without window manager.
```
mainWindow = new BrowserWindow({
      frame: false,
      width: 1440, // Window size must 
      height: 900, // match the current display resolution
      fullscreen: true,
      backgroundColor: '#ececec'
```

Maybe possible to check display resolution before render BrowserWindow and set the right window size?

**Comment by diastremskii** [comment]
Yep, it's possible to get resolution before opening main window.

I [created a branch](https://github.com/TheBeastOfCaerbannog/magic-setup-assistant/tree/fix/fullscreen) for this change and will open PR after setting up raw `Xorg `environment to test it.

**Comment by zhovner** [comment]
> I created a branch for this change

I've tested and it works as expected.

> after setting up raw Xorg environment

Follow this steps:

### disable graphics interface at startup
`systemctl set-default multi-user.target`

### create ~/.xinitrc file
```
#!/bin/sh
xrandr --output Virtual1 --mode 1440x900
cd ~/magic-setup-assistant/
npm start
```

### start Xorg manually
`startx`

**Comment by diastremskii** [comment]
Oh, thank you. Sorry, was a bit busy today. Opened #14
